import type { Metadata } from 'next'
import Link from 'next/link'
import Logo from '@/components/logo'

export const metadata: Metadata = {
  title: 'Terms of Service — Finia',
  description: 'Terms and conditions governing the use of the Finia mobile app, WhatsApp assistant and website.',
}

export default function TermsPage() {
  return (
    <div className="legal-page wrap">
      <Link href="/" className="legal-back">← Back to Finia</Link>

      <div className="legal-head">
        <Logo />
        <h1 className="h-sec" style={{ marginTop: 22 }}>Terms of Service</h1>
        <p className="legal-updated">Last updated: June 21, 2026</p>
      </div>

      <div className="legal-notice">
        This document is a general template provided for transparency purposes and does not constitute
        legal advice. Finia should have these Terms reviewed by qualified legal counsel in each
        jurisdiction where the service is offered before relying on them as a binding agreement.
      </div>

      <div className="legal-content">
        <h2>1. Acceptance of Terms</h2>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of the Finia mobile application,
          the Finia WhatsApp assistant, and the website at finanzas-ia.app (together, the &quot;Service&quot;),
          operated by Finia (&quot;Finia&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By creating an account, linking your
          WhatsApp number, or otherwise using the Service, you agree to be bound by these Terms and by our
          <Link href="/privacy"> Privacy Policy</Link>. If you do not agree, do not use the Service.
        </p>

        <h2>2. Description of the Service</h2>
        <p>
          Finia is a personal finance assistant that lets you record income and expenses, set budgets and
          savings goals, and review reports, either through the mobile app or by sending text, voice notes,
          or photos of receipts via WhatsApp. The Service uses artificial intelligence (&quot;AI&quot;) to classify
          transactions, detect recurring subscriptions, and generate financial summaries.
        </p>
        <p>
          <strong>Finia is not a bank, a financial advisor, a broker, or an investment service.</strong>{' '}
          Information, summaries, and suggestions generated by the AI are provided for informational and
          organizational purposes only and do not constitute financial, tax, legal, or investment advice.
          You are solely responsible for any financial decisions you make.
        </p>

        <h2>3. Eligibility and Account Registration</h2>
        <p>
          You must be at least 18 years old, or the age of legal majority in your jurisdiction, to use the
          Service. You agree to provide accurate registration information and to keep your credentials and
          linked WhatsApp number secure. You are responsible for all activity that occurs under your account.
        </p>

        <h2>4. Subscriptions, Trials, and Billing</h2>
        <p>
          Certain features require a paid subscription (&quot;Premium&quot;). Free trials, where offered, automatically
          convert into a paid subscription unless cancelled before the trial ends. Subscriptions purchased
          through the mobile app are billed and managed by Apple App Store or Google Play via RevenueCat;
          subscriptions purchased through the website are billed by Stripe. Prices, currencies, and billing
          cycles are displayed at the time of purchase and may vary by region.
        </p>
        <p>
          You can cancel your subscription at any time through your App Store/Play Store account settings
          or, for web purchases, through the link provided in your confirmation email. Cancellation stops
          future renewals; we do not provide refunds for partial billing periods except where required by
          applicable consumer protection law.
        </p>

        <h2>5. WhatsApp Channel</h2>
        <p>
          The WhatsApp assistant is provided via the WhatsApp Business Platform and a third-party messaging
          provider (Twilio). Standard data and messaging rates from your carrier may apply. Messages you send
          to the assistant, including text, audio, and images, are processed by our servers and by AI model
          providers to deliver the Service, as described in our <Link href="/privacy">Privacy Policy</Link>.
        </p>

        <h2>6. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any unlawful purpose or in violation of any applicable regulation;</li>
          <li>Attempt to reverse engineer, decompile, or interfere with the Service&apos;s infrastructure or security;</li>
          <li>Upload content that is fraudulent, abusive, or infringes third-party rights;</li>
          <li>Use the Service to process financial data belonging to someone else without their consent.</li>
        </ul>

        <h2>7. Intellectual Property</h2>
        <p>
          The Service, including its name, logo, design, and underlying software, is owned by Finia and
          protected by intellectual property laws. We grant you a limited, non-exclusive, non-transferable
          license to use the Service for personal, non-commercial purposes.
        </p>

        <h2>8. Disclaimers and Limitation of Liability</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot;, without warranties of any kind. AI-generated
          classifications and insights may contain errors; you should review transactions for accuracy. To
          the maximum extent permitted by law, Finia shall not be liable for indirect, incidental, or
          consequential damages, or for financial losses arising from decisions made based on the Service.
        </p>

        <h2>9. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service if you breach these Terms or misuse the
          Service. You may stop using the Service and request deletion of your account at any time, as
          described in our <Link href="/privacy">Privacy Policy</Link>.
        </p>

        <h2>10. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will be notified through the app or
          by email. Continued use of the Service after changes take effect constitutes acceptance of the
          revised Terms.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the Argentine Republic, without prejudice to any mandatory
          consumer protection rights you may have under the laws of your country of residence.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these Terms can be sent to <a href="mailto:support@finanzas-ia.app">support@finanzas-ia.app</a>.
        </p>
      </div>
    </div>
  )
}
